Lista de exercícios 02: Q1/1.cpp File Reference
1.cpp File Reference
Documentação Questão1.
#include <iostream>
Functions
int tribonacciRecursiva (int numero)
Funcao que calcula o n-ésimo termo da sequencia tribonacci.
int tribonacciIterativa (int numero)
Funcao que calcula o n-ésimo termo da sequencia tribonacci.
int main (int argc, char const *argv[])
Detailed Description
Documentação Questão1.
Author
Carlos Pinheiro - 20220030194
Definition in file 1.cpp.
Function Documentation
main()
int main (int argc, char const * argv[])
Definition at line 45 of file 1.cpp.
{
     int n1 = 3;
     int n2 = 5;
     int n3 = 6;
     int n4 = 7;
     //Testes
     std::cout << tribonacciRecursiva(n1) << std::endl;
     std::cout << tribonacciRecursiva(n2) << std::endl;
     std::cout << tribonacciRecursiva(n3) << std::endl;
     std::cout << tribonacciRecursiva(n4) << std::endl;
     std::cout << std::endl;
     std::cout << tribonacciIterativa(n1) << std::endl;
     std::cout << tribonacciIterativa(n2) << std::endl;
     std::cout << tribonacciIterativa(n3) << std::endl;
     std::cout << tribonacciIterativa(n4) << std::endl;
     return 0;
 }
References tribonacciIterativa(), and tribonacciRecursiva().
tribonacciIterativa()
int tribonacciIterativa (int numero)
Funcao que calcula o n-ésimo termo da sequencia tribonacci.
Parameters
numero = indice do termo da sequencia
Returns
o numero correspondente ao indice informado
Definition at line 28 of file 1.cpp.
{
     if (numero == 0 || numero == 1){
         return 0;
     } else if(numero == 2){
         return 1;
     } else {
         int trib0 = 0, trib1 = 0, trib2 = 1, tribN;
         for (int i = 3; i <= numero; i++){
             tribN = trib0 + trib1 + trib2;
             trib0 = trib1;
             trib1 = trib2;
             trib2 = tribN;
         }
         return tribN;
     }
 }
Referenced by main().
tribonacciRecursiva()
int tribonacciRecursiva (int numero)
Funcao que calcula o n-ésimo termo da sequencia tribonacci.
Parameters
numero = indice do termo da sequencia
Returns
o numero correspondente ao indice informado
Definition at line 13 of file 1.cpp.
{
     if (numero == 0 || numero == 1){
         return 0;
     } else if(numero == 2){
         return 1;
     } else {
         return tribonacciRecursiva(numero - 1) + tribonacciRecursiva(numero - 2) + tribonacciRecursiva(numero - 3);
     }
 }
Referenced by main().