Lista de exercícios 02: Q3/main.cpp File Reference
main.cpp File Reference
Documentação Questão3.
#include "Aluno.h"
#include "Turma.h"
#include <iostream>
#include <algorithm>
#include <string>
Functions
int main (int argc, char const *argv[])
Variables
string nomes [50]
Detailed Description
Documentação Questão3.
Author
Carlos Pinheiro - 20220030194
Definition in file main.cpp.
Function Documentation
main()
int main (int argc, char const * argv[])
Definition at line 78 of file main.cpp.
{
     Turma turma(8);
     turma.alocaAlunos();
     int entrada;
     do {
         cout << "|      Menu inicial      |" << endl;
         cout << "__________________________" << endl;
         cout << "|    1 - Listar alunos   |" << endl;
         cout << "|    2 - Ordenar alunos  |" << endl;
         cout << "|    3 - Sair            |" << endl;
         cout << "__________________________" << endl;
         cout << "   Digite uma das opções  " << endl;
         cin >> entrada;
         if(entrada == 1){
             turma.imprimeAlunos();
         } else if(entrada == 2){
             int entrada2;
             do {
                 cout << "|      Ordenar por       |" << endl;
                 cout << "__________________________" << endl;
                 cout << "|    1 - Matricula       |" << endl;
                 cout << "|    2 - Nome            |" << endl;
                 cout << "|    3 - Nota            |" << endl;
                 cout << "|    4 - Sair            |" << endl;
                 cout << "__________________________" << endl;
                 cout << "   Digite uma das opções  " << endl;
                 cin >> entrada2;
                 if(entrada2 == 1){
                     turma.ordenaCampo("matricula");
                     turma.imprimeAlunos();
                     cout << "Lista ordenada com sucesso!\n" << endl;
                     entrada2 = 4;
                 } else if (entrada2 == 2){
                     turma.ordenaCampo("nome");
                     turma.imprimeAlunos();
                     cout << "Lista ordenada com sucesso!\n" << endl;
                     entrada2 = 4;
                 } else if (entrada2 == 3){
                     turma.ordenaCampo("nota");
                     turma.imprimeAlunos();
                     cout << "Lista ordenada com sucesso!\n" << endl;
                     entrada2 = 4;
                 } else {
                     cout << "Informe uma opção válida" << endl;
                 }
             } while (entrada2 != 4);
         }
     } while (entrada!=3);
     return 0;
 }
References Turma::alocaAlunos(), Turma::imprimeAlunos(), and Turma::ordenaCampo().
Variable Documentation
nomes
string nomes[50]
Initial value:
= {"Ana", "Bianca", "Carlos", "Daniel", "Eduarda", "Fabio", "Gabriela", "Henrique", "Isabela", "João",
                        "Karen", "Lucas", "Mariana", "Natalia", "Oscar", "Pedro", "Quintino", "Raquel", "Sofia", "Tomas",
                        "Ubiratan", "Valentina", "Wagner", "Xavier", "Yuri", "Zilda", "Aline", "Bruno", "Cristina", "Diego",
                        "Elias", "Fernanda", "Gustavo", "Helena", "Ivan", "Julia", "Karina", "Leonardo", "Marta", "Nelson",
                        "Olga", "Paulo", "Queila", "Rafael", "Samantha", "Thiago", "Ulisses", "Vanessa", "Wilma", "Yago"}
Definition at line 15 of file main.cpp.
Referenced by Turma::alocaAlunos().